---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apache-rs
spec:
  replicas: 2
  selector: 
    matchLabels:
      apache: web
  template:
    metadata:
      labels:
        apache: web
    spec:
      containers:
      - name: apache
        image: httpd:latest
        env:
        - name: WEBPORT
          value: "9000"
        volumeMounts:
        - name: conf
          mountPath: /usr/local/apache2/conf
        - name: index
          mountPath: /usr/local/apache2/htdocs
        ports:
        - name: webport
          containerPort: 9000
          protocol: TCP
      volumes:
      - name: conf
        configMap:
          name: apache-conf
      - name: index
        configMap:
          name: apache-html
