---
apiVersion: v1
kind: Pod
metadata: 
  name: pod-wp
  labels:
    app: wordpress
spec:
  containers:
  - image: wordpress
    name: wp
    env:
      - name: WORDPRESS_DB_HOST
        value: mysql
      - name: WORDPRESS_DB_USER
        value: wp-admin
      - name: WORDPRESS_DB_PASSWORD
        value: dkagh1.
      - name: WORDPRESS_DB_NAME
        value: wordpress
    ports:
    - name: wordpress
      containerPort: 80
    volumeMounts:
    - name: wp-pv
      mountPath: /var/www/html
  volumes:
  - name: wp-pv
    persistentVolumeClaim:
      claimName: wp-pvc