---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-cm
spec:
  containers:
  - image: c1t1d0s7/myweb:customport
    name: myapp
    env:
    - name: WEBPORT
      valueFrom:
        configMapKeyRef:
          name: myapp-pod-options
          key: webport
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: myapp-pod-options
          key: message
    args:
    - $(MESSAGE)
    ports:
    - containerPort: 8088
      protocol: TCP